environment:
  matrix:
    - PYTHON: C:\Python35
    - PYTHON: C:\Python36

build: off

init:
  - SET CI=True
  - SET APPVEYOR=True
  - SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - SET PYTHONIOENCODING=utf-8
  - SET PYTHONPATH=%APPVEYOR_BUILD_FOLDER%

install:
  - pip install -U pip
  - pip install pipenv
  - pipenv install

test_script:
  - pipenv run coverage run tests/runtests.py

branches:
  only:
    - master

notifications:
  - provider: Email
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
